apiVersion: apps/v1
kind: Deployment
metadata:
  name: competition
  namespace: competition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master-dev
      containers:
        - name: my-container
          image: wycca1/competition:1.1.9
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: data-volume
              mountPath: /data
              mountPath: /data
      serviceAccountName: competition  
      serviceAccount: competition
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: competition-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: competition-service
  namespace: competition
spec:
  selector:
    app: my-app
  type: NodePort  # Add this line to specify NodePort type
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: competition
  namespace: kubeflow
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - headers:
      request:
        add:
          x-forwarded-prefix: /competition
    match:
    - uri:
        prefix: /competition/
    rewrite:
      uri: /
    route:
    - destination:
        host: competition-service.competition.svc.cluster.local
        port:
          number: 8888

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: competition-pvc
  namespace: competition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client  # Add this line to specify the storage class


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: competition
  namespace: competition

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: competition-role
  namespace: competition
rules:
- apiGroups: ["kubeflow.org"]
  resources: ["profiles"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: competition-role-binding
  namespace: competition
subjects:
- kind: ServiceAccount
  name: competition
  namespace: competition
roleRef:
  kind: ClusterRole
  name: competition-role
  apiGroup: rbac.authorization.k8s.io



